# Generated by Django 4.1.3 on 2022-12-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
