# Generated by Django 4.1.3 on 2022-12-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_student_std_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_first_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='std_last_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_birth_date',
            field=models.DateField(),
        ),
    ]
