# Generated by Django 4.1.3 on 2022-12-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_student_std_first_name_student_std_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='std_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='std_first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='std_last_name',
            field=models.CharField(max_length=200),
        ),
    ]
